include config.mk
$(info    BOOST_ROOT is $(BOOST_ROOT))
$(info    BOOST_INCLUDEDIR is $(BOOST_INCLUDEDIR))
$(info    BOOST_LIBRARYDIR is $(BOOST_LIBRARYDIR))
$(info    CPPFLAGS is $(CPPFLAGS))
$(info    LDFLAGS is $(LDFLAGS))
